### ISSUE TITLE
FMA:86103 (region of organ component) causing problems

### ISSUE THREAD

**Issue by patrick-lloyd-ray** [addiehl/neurological-disease-ontology#3]
When I open ND.owl and turn on the reasoner, quite a few classes are placed under owl:Nothing. I scanned some of the explanations and it seemed that FMA:86103 (region of organ component) was perhaps the source of these problems (it is classified as a subclass of 'cardinal organ part' or 'anatomical structure', which it shouldn't be, IMO). It looks like @APCox beat me to this realization and annotated FMA:86103 in ND.owl with a curator note to this effect. 

I don't know whether FMA is active. It doesn't appear it is and looking around various discussions in OBO-land leads me to conclude that it is complicated to say the least. I know that FMA is logically incoherent and this causes problems like the one above. Also, they are not generally OBO-compliant, which would make integration a bit more difficult than with OBO-compliant ontologies. So, even if FMA were active and responsive to requests, I don't know that FMA curators would solve the issues that are causing problems here.

Out of curiosity, what is the rationale for using FMA over UBERON for the imported anatomical classes for this project?

**Comment by addiehl** [comment]
In fact, Alex and I have recently discussed swapping in Uberon classes for the FMA classes in ND.  Not sure how soon this will happen, but hopefully this summer.

**Comment by patrick-lloyd-ray** [comment]
That's great news. UBERON has been undergoing some improvements specifically in neuroanatomy recently so hopefully it will have good coverage. I think their responsiveness to new term requests is also pretty good (IMO). Depending on what needs done, I might also be able to help or review. Thanks!
